name: Deploy to AWS ECR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-1  # ✅ 指定 AWS 区域
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t jsherp -f ./jshERP-boot/Dockerfile ./jshERP-boot 

    - name: Build Frontend Docker image
      run: |
        docker build -t jsherp-web -f ./jshERP-web/Dockerfile ./jshERP-web 

    - name: Tag image
      run: |
        docker tag jsherp:latest ${{ secrets.ECR_REPOSITORY }}:latest
        docker tag jsherp-web:latest 696899996656.dkr.ecr.ap-southeast-1.amazonaws.com/jsherp-web:latest

    - name: Push image to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest
        docker push 696899996656.dkr.ecr.ap-southeast-1.amazonaws.com/jsherp-web:latest
