name: Deploy to AWS ECR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t jsherp -f ./jshERP-boot/Dockerfile ./jshERP-boot 

    - name: Tag image
      run: |
        docker tag jsherp:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push image to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest
